spring:
  application:
    name: serviceA
server:
  port: 8014

druid:
  url: jdbc:mysql://localhost:3306/user?characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&useSSL=false
  driverClass: com.mysql.cj.jdbc.Driver
  username: root
  password: root
  initialSize: 5
  minIdle: 1
  maxActive: 100
  testOnBorrow: true
  validationQuery: SELECT 1

mybatis:
  type-aliases-package: com.example.testa.dao.model
  mapper-locations: classpath:sqlmap/*.xml